config/routes.rb
CoursesCatalog::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
  resources :courses do
    resources :track_its, only: [:create, :destroy]
    resources :start_dates
    collection do
      get 'pending_list'
    end
  end
  resources :track_its, only: [:index]
  root :to => 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  respond_to :html, :json
  
  def index
    @courses = @courses.with_closest_start_date.publish_only
    @track_course_ids =  user_signed_in? ? current_user.track_its.pluck(:course_id).uniq : []

    respond_to do |format|
      format.html
      format.json { render json: CoursesDatatable.new(view_context, @courses, @track_course_ids) }
    end
  end

  def pending_list
    @courses = @courses.where("publish_status = ? OR id IN (?)", "pending", StartDate.pending_only.pluck(:course_id).uniq )
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    respond_with(@course)
  end

  def edit
    respond_with(@course)
  end

  def create
    flash[:notice] = 'Course was successfully created.' if @course.save
    respond_with(@course)
  end

  def update
    authorize! :publish, @course if params[:course] && params[:course][:publish_status] == "publish"

    flash[:notice] = 'Course was successfully updated.' if @course.update_attributes(params[:course])
    respond_with(@course)
  end

  def destroy
    @course.destroy
    flash[:notice] = 'Course was successfully deleted.'
    respond_with(@course)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_alert_msgs.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <div class="alert fade in alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/courses/_form.html.erb
<div class="page-header">
  <h1><%= controller.action_name.capitalize + " " + controller.controller_name.singularize.capitalize %></h2>
</div>

<div id="alert-area"></div>

<%= simple_form_for @course, :html => { :class => 'form-horizontal course-edit' } do |f| %>

  <%= render 'alert_msgs', object: @course %>

  <fieldset> 
    <%= f.input :name, :required => true, :input_html => {:class => "input-block-level"} %>
    <%= f.input :link, :required => true, :input_html => {:class => "input-block-level"} %>
    <%= f.input :desc, :input_html => {:class => "input-block-level wysihtml5"} %>
    
    <%= f.input :start_by_schedule,:label => false, :inline_label => 'Start by schedule', :input_html => { :onclick => "$('.control-group.start-dates-list').toggle()" } %>
    <% unless %w[new create].include?(controller.action_name) %>
      <div class="control-group start-dates-list" <%=raw !@course.start_by_schedule ? ' style="display: none;" ' : '' %> >
        <label class="string control-label">Start Dates</label>
        <div class="controls">
          <%= render 'courses/start_dates' %>
        </div>
      </div>
    <% end %>

    <% if current_user.admin? %>
      <%= f.input :publish_status, :collection => Course::PUBLISH_STATUS, :include_blank => false %>
    <% end %>
  </fieldset> 

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', courses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/courses/_start_dates.html.erb
<div class="start-dates-list-widget" id="start-dates-list-widget" data-course-id="<%= @course.id %>">
  
  <div class="header">
    <a data-toggle="collapse" href="#start-dates-list-collapse">
      <%= glyph('chevron-up') %><%= glyph('chevron-down') %>
      <h5>Start Dates</h5>
    </a>
  </div>
  
  <div id="start-dates-list-collapse" class="body collapse in">
    <fieldset>
      <% if %w[edit].include?(controller.action_name) || @course.start_by_schedule %>
        <%= render (user_signed_in? && current_user.admin? ? "admin/courses/start_dates_list" : "courses/start_dates_list"), :mustache => {course_id: @course.id, start_dates: @course.start_dates.accessible_by(current_ability).to_a} %> 
      <% else %>
        <span class="label label-success">Always open</label>
      <% end %>
    </fieldset>

    <% if can?(:create, StartDate) && (%w[edit].include?(controller.action_name) || @course.start_by_schedule ) %>
      <div class="footer">
        <input id="datepicker">
        <%= link_to "+ Add", "#", class: "add-date btn btn-mini" %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<div class="page-header">
  <h1><%= controller.controller_name.capitalize %></h1>
</div>

<div id="alert-area"></div>

<table id="courses-list" class="display table table-striped" data-source="<%= courses_url(format: "json") %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  </tbody>

</table>

<%= link_to 'New', new_course_path, :class => 'btn btn-primary' if can?(:create, Course) %>

app/views/courses/new.html.erb
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<div class="course-show <%= dom_id(@course) %>">
  <div id="alert-area"></div>

  <h3>
    <%= @course.name %>
    <% if @course.publish? %>
      <%= link_to course_track_its_path(@course), class: 'btn btn-mini track-it', format: :json, remote: true, method: :post  do %><%= glyph('eye-open') %> Trak it</a> <% end %>
    <% else %>
      <%= show_publish_status(@course) %> 
    <% end %>
  </h3>

  <%= render 'courses/start_dates' %>

  <dl>

    <% if !@course.link.blank? %>
      <dt>Link:</dt>
      <dd><%= link_to @course.link, @course.link, target: "_blank" %></dd>
    <% end %>


    <% if !@course.desc.blank? %>
      <dt>About:</td>
      <dd><%=raw @course.desc %></dd>
    <% end %>
  </dl>

  <div class="clear"></div>
  <% if can? :manage, @course %>
    <div class="form-actions">
      <%= link_to 'Edit', edit_course_path(@course), :class => 'btn' %>
      <%= link_to 'Destroy', course_path(@course), :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %>

      <% if @course.draft? %>
        <%= link_to 'Publish', course_path(@course, :course => { :publish_status => (can?(:publish,@course) ? "publish" : "pending") }), :class => 'btn', :method => :put %>
      <% end %>

      <% if @course.pending? && current_user.admin? %>
        <%= link_to 'Approve', course_path(@course, :course => { :publish_status => "publish" }), :class => 'btn', :method => :put %>
        <%= link_to 'Not Approve', course_path(@course, :course => { :publish_status => "draft" }), :class => 'btn', :method => :put %>
      <% end %>

    </div>
  <% end %>
</div>